var http="http://www.ciads.com/templets/default";
var url=new Array();
url[0]=http+"/theme/bg/ib_01.png";
url[1]=http+"/theme/bg/Apc.gif";
url[2]=http+"/theme/bg/flm.gif";
url[3]=http+"/theme/bg/ib_02.png";
url[4]=http+"/theme/bg/ib_03.png";
url[5]=http+"/theme/bg/set.gif";
url[6]=http+"/theme/bg/com.gif";
url[7]=http+"/theme/bg/fCb.png";
url[8]=http+"/theme/bg/nkt.png";
url[9]=http+"/theme/bg/ss.gif";
url[10]=http+"/theme/bg/map.gif";
url[11]=http+"/theme/bg/nht.png";
url[12]=http+"/theme/bg/k02.gif";
url[13]=http+"/theme/bg/ms.gif";
url[14]=http+"/theme/bg/nbg.gif";
$(window).load(function(){loadImage(url,0);});
function loadImage(u,i) {var img = new Image();img.src = u[i];$(img).load(function(){if(i<u.length-1){loadImage(u,++i);}});$(img).error(function(){if(i<u.length-1){loadImage(u,++i);}});};